#+TITLE: Dirty duck: A triage's guided tour
#+AUTHOR: Center of Data Science for Public Policy
#+EMAIL: adolfo@uchicago.edu
#+STARTUP: showeverything
#+STARTUP: nohideblocks
#+STARTUP: Indent


* Welcome!

This tutorial will show you how to use =triage=, a data science
 modeling tool developed in  the [[http://dsapp.uchicago.edu][Center for Data Science and Public
 Policy]] (DSaPP) at the University of Chicago. 

=triage= aims to help you to model two complex data problems: /Early
warning systems/ and /resource prioritization/. 
Both problems pop up constantly in our daily job at DsaPP. This
problems serve as templates for real use cases of Data Science and
Machine Learning in the public policy sector.

This problems are difficult to model due the fact that they are prone
to errors in the conceptualization of the problem or in the
implementation of the model in a computer. The multi dimensional,
multi entities time series structure of both problems is the cause of
these difficulties. 

* What do you need for this tutorial?

[[http://www.docker.com][Docker CE]] and [[https://docs.docker.com/compose/][Docker Compose]] installed. That's it.
Use the links for installing instructions.

Note that if you are using =GNU/Linux= you should add your user to the
=docker= group following the guidance at this [[https://docs.docker.com/install/linux/linux-postinstall/][link]].

At the moment only operative systems with /real/ command lines are
supported, as =GNU/Linux= and =MacOS=. Maybe in a recent version of
=Windows= you could install a =bash= command line. 

* How to use this tutorial?

Clone this repository in your Laptop 

#+BEGIN_EXAMPLE
 git clone https://github.com/dssg/dirtyduck.git
#+END_EXAMPLE

Then copy the file 
=infrastructure/food_db/.env_example= to
=infrastructure/food_db/.env= then open the file and change the
string =your_password= for something more meaningful to you.

   #+BEGIN_EXAMPLE sh :tangle infrastructure/env_example
    POSTGRES_DB=food
    POSTGRES_HOST=0.0.0.0
    POSTGRES_USER=food_user
    POSTGRES_DB=food
    POSTGRES_PORT=5434
    POSTGRES_PASSWORD=your_password  #<-- change this if you like

    UID=1000
    GID=1000
   #+END_EXAMPLE

And then run

#+BEGIN_EXAMPLE
./tutorial.sh start
#+END_Example

This will take some minutes the first time.

Finally open your browser and type in the location bar =0.0.0.0= that
will open the tutorial, follow from there[fn:3].

* I want to help

Help is always welcome! How do you want to help? You can help
reporting errors, improving the tutorial or proposing improvements to
=triage=. This three cases are discussed below.

** How can I report errors?

We are almost sure that there will be errors, please open an [[https://github.com/dssg/dirtyduck/issues][issue]] and
we will try to correct them as soon as possible.

** How can I improve the tutorial itself?

This tutorial was created following the practices of [[https://www-cs-faculty.stanford.edu/~knuth/lp.html][Literate
Programming]] using  [[https://orgmode.org/][org-mode]][fn:1] in [[https://www.gnu.org/software/emacs/][GNU Emacs]][fn:2]. That means that
the tutorial is a /live/ document that mixes programming languages and
text.  

The steps to help are:

- clone the repository
- edit the source =org= files in the =src= folder
- create a *pull request*.


** How can I collaborate developing =triage=?

Go to the [[https://github.com/dssg/triage][triage]] repository and follow the instructions there.

* Footnotes

[fn:3] You could also follow this tutorial in github or in your =GNU
Emacs=. Just follow the =org= files inside the folder =src=.

[fn:2] But it is supported in =vim= if you install a plugin.

[fn:1] Is very similar to =markdown= so, you won't have any problem.
