# CHOOSE MODEL GROUPS
model_groups:
    query: |
        SELECT DISTINCT(model_group_id)
        FROM model_metadata.model_groups
# CHOOSE TIMESTAMPS/TRAIN END TIMES
time_stamps:
    query: |
        SELECT DISTINCT train_end_time
        FROM model_metadata.models
        WHERE model_group_id IN ({})
        AND EXTRACT(DAY FROM train_end_time) IN (1)
        AND train_end_time >= '2015-01-01'
# FILTER
filter:
    metric: 'precision@' # metric of interest
    parameter: '10_pct' # parameter of interest
    max_from_best: 1.0 # The maximum value that the given metric can be worse than the best model for a given train end time.
    threshold_value: 0.0 # The worst absolute value that the given metric should be.
    distance_table: 'distance_table' # name of the distance table
    models_table: 'models' # name of the models table

# RULES
rules:
    -
        shared_parameters:
            -
                metric: 'precision@'
                parameter: '10_pct'

        selection_rules:
            -
                name: 'best_current_value' # Pick the model group with the best current metric value
                n: 3
            -
                name: 'best_average_value' # Pick the model with the highest average metric value
                n: 3
            -
                name: 'lowest_metric_variance' # Pick the model with the lowest metric variance
                n: 3
            -
                name: 'most_frequent_best_dist' # Pick the model that is most frequently within `dist_from_best_case`
                dist_from_best_case: [0.05]
                n: 3
